name: CI/CD with Sentry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./src/my-sentry-app

      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1
        with:
          version: latest # optional if 'latest'
          token: ${{ SECRETS.SENTRY_AUTH_TOKEN }} # from GitHub secrets
          organization: ${{ secrets.SENTRY_ORG }}
          project: ${{ secrets.SENTRY_PROJECT }}

      - name: Run tests and generate logs
        run: |
          mkdir -p ./logs
          npm test | tee ./logs/test-output.log
        working-directory: ./src/my-sentry-app
        continue-on-error: true  # Continue even if tests fail

#      - name: Check if tests failed
#        if: failure()  # Runs if the previous step failed
#        run: |
#          echo "Tests failed, sending event to Sentry"
#          sentry-cli send-event -m "Test failures detected" --logfile ./logs/test-output.log
##        env:
##          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
##          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
#        continue-on-error: true  # Ensure the rest of the workflow continues
      - name: Check if log file contains errors
        run: |
          if grep -q "error" ./logs/test-output.log; then
            echo "Errors found in the test log. Sending event to Sentry."
            sentry-cli send-event -m "Test failures detected" --logfile ./logs/test-output.log
          else
            echo "No errors found in the test log."
          fi
        working-directory: ./src/my-sentry-app