name: CI/CD with Sentry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./src/my-sentry-app

      - name: Run tests
        run: npm test
        working-directory: ./src/my-sentry-app

      - name: Create Sentry Release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}  # Ensure your SENTRY_AUTH_TOKEN is stored in GitHub secrets
          SENTRY_PROJECT: 'node-express-app-minordevops'  # Replace with your actual Sentry project slug
          SENTRY_ORG: 'gus-bj'  # Replace with your actual Sentry organization slug
        run: |
          npx sentry-cli releases new --project $SENTRY_PROJECT --org $SENTRY_ORG $GITHUB_SHA
          npx sentry-cli releases set-commits --auto $GITHUB_SHA

      - name: Send test errors to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          npx sentry-cli send-event -m "Test errors during deployment" --level error
        working-directory: ./src/my-sentry-app
