name: CI/CD with Sentry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./src/my-sentry-app

      - name: Setup Sentry CLI
        uses: getsentry/action-setup-sentry-cli@v1
        with:
          version: latest # optional if 'latest'
          token: ${{ SECRETS.SENTRY_AUTH_TOKEN }} # from GitHub secrets
          organization: ${{ secrets.SENTRY_ORG }}
          project: ${{ secrets.SENTRY_PROJECT }}

      - name: Run tests and generate logs
        run: |
          mkdir -p ./logs
          npm test | tee ./logs/test-output.log
        working-directory: ./src/my-sentry-app
        continue-on-error: true  # Continue even if tests fail

      - name: Upload test log to Sentry
        run: |
          sentry-cli releases files $GITHUB_SHA upload ./logs/test-output.log test-output.log
